### ISSUE TITLE
Remove "Not avaliable" in weapon shop and equip-weapon menu

### ISSUE THREAD

**Issue by hhaslam11** [hhaslam11/Text-Fighter#11]

**Comment by htn17** [comment]
Do you want the word NOT AVAILABLE removed? Wasn't it there to confirm its not available for equipping?

**Comment by hhaslam11** [comment]
@htn17 Instead of showing "NOT AVAILABLE", I wanted to just make it not show up at all (But keep the ordering)
For example

```
1) Nothing (NOT AVAILABLE)
2) Pistol
```

would just be

`1) Pistol`

It would look cleaner, IMO.

**Comment by htn17** [comment]
Then, doesn't removing:

Ui.println((i + 1) + ") " + arrayWeapon.get(i).getName().toUpperCase() + " IS NOT AVAILABLE");

fix the problem?

**Comment by hhaslam11** [comment]
Yes,  removing that would work,  except the numbering would look weird (with missing numbers); which,  as you said,  could be solved by using a different variable

**Comment by htn17** [comment]
Now that I looked at this, there might be a flaw. I'll need to think about
it a bit more.
I'm considering using a mapping.

**Comment by htn17** [comment]
I fixed it. Note, I have not tested all the possible defects. Currently, it
works if only basic usage.

**Comment by hhaslam11** [comment]
Seems to work fine as far as I can tell, thanks :)
