### ISSUE TITLE
add contributers list to readme and an ingame-menu (credits menu)?

### ISSUE THREAD

**Issue by hhaslam11** [hhaslam11/Text-Fighter#113]
There's been a  lot of awesome people helping out recently, and they deserve some credit!

**Comment by R1ndT** [comment]
Hello,
I would love to help with that! Since I am new to GitHub and pretty much to Java, this would serve me as a great introduction to both of those.

Thanks in advance
RindT

**Comment by hhaslam11** [comment]
#118
