### ISSUE TITLE
Adding exit options during Game setup

### ISSUE THREAD

**Issue by docschorsch** [hhaslam11/Text-Fighter#116]
Hello there, 
in the Game setup screens (before starting the actual game) I was stumbling over the missing option to come back to the Start, e.g. in Game class. May I suggest to add the option to come back, for instance with a consistent 0) Exit option that takes the user back to main? I will be happy to work on this issue if assigned to me:)
Cheers from Berlin

**Comment by hhaslam11** [comment]
Sounds good, definitely feel free to work on it. Thanks!

**Comment by hhaslam11** [comment]
added with #117
