### ISSUE TITLE
Make Ui.cls() less hacky.

### ISSUE THREAD

**Issue by hhaslam11** [hhaslam11/Text-Fighter#38]
More legit. Printing a bunch of blank lines is bad coding, and inefficient.

**Comment by BrendonButler** [comment]
Did not mean to directly commit without a PR. Hopefully, this is not an issue!

**Comment by hhaslam11** [comment]
> 
> 
> Did not mean to directly commit without a PR. Hopefully, this is not an issue!

I didn't even realize you had permission to do that, aha- but It's definitely okay, thanks! Definitely a much better way of clearing the screen.
