### ISSUE TITLE
Crashes when using "givemeitall" cheat

### ISSUE THREAD

**Issue by hhaslam11** [hhaslam11/Text-Fighter#49]
To reproduce:

- Go to main menu
- Open cheat menu by typing in 0
- Type in `givemeitall`

**Comment by MathewPhoenix** [comment]
Resource: Cheats.java
Line: 44
{
for(int i = 0; i <= Weapon.arrayWeapon.size(); i++){
}
-> for(int i = 0; i < Weapon.arrayWeapon.size(); i++){
I think it can fix it.
