### ISSUE TITLE
File Save/Load system error

### ISSUE THREAD

**Issue by MathewPhoenix** [hhaslam11/Text-Fighter#50]
Hi,my name is Mathew.

To reproduce:
1. create a new user profile
2. exit the program
3. use the user name to enter the save game
4. Cannot find save file. 

Solution:
Resource: SaveAndLoad.java
Line: 171
{
path = path.replace(".jar", User.name());
}
-> path = path.replace(".jar","_"+User.name());
Hope it help.
I love this game :)

**Comment by hhaslam11** [comment]
Thanks, somehow never noticed that!
