### ISSUE TITLE
Use either tabs or spaces. Not both.

### ISSUE THREAD

**Issue by hhaslam11** [hhaslam11/Text-Fighter#54]
![91c9ebe4ba71eab744c05725cbcd42b6](https://cloud.githubusercontent.com/assets/9996803/17010293/5f9e44fc-4eb7-11e6-9c22-af73f7efc59e.jpg)

**Comment by MathewPhoenix** [comment]
lol,exactly!
 Check this funny video: https://youtu.be/SsoOG6ZeyUI

**Comment by hhaslam11** [comment]
That scene is actually one of the reasons this was brought to my attention in the first place! Love silicon Valley <3
