### ISSUE TITLE
Can't go back on 1st attempt when betting with insufficient coins.

### ISSUE THREAD

**Issue by CLEMENTJOHNSHAJI** [hhaslam11/Text-Fighter#98]
While betting with an insufficient amount of coins in Dice game, it shows a warning message "You do not have enough coins. Please enter a smaller amount, or type 0 to go back."
But on the 1st attempt of entering "0", instead of redirecting back, "0" is repeated once again on next line. Only on the  2nd attempt of entering "0", redirects the user back.
[eg: 
![commandpromptjavajartext](https://user-images.githubusercontent.com/17124690/47115077-2d1a5e00-d266-11e8-8fd5-1130bb6c6e5b.gif)
Dice Game  Go to the town-> Casino->Dice Game]

**Comment by CLEMENTJOHNSHAJI** [comment]
Thanks for confirming. Can I contribute to this issue?

**Comment by hhaslam11** [comment]
@CLEMENTJOHNSHAJI of course, contributions are welcome and appreciated :smile:

**Comment by BrendonButler** [comment]
Running Java 8 1.8.0_181 I could not replicate this issue. I thought it may have something to do with the [Scanner Infinite Loop issue](https://stackoverflow.com/questions/1794281/java-infinite-loop-using-scanner-in-hasnextint), but it just worked for me.

I only tested by cutting out the [getValidInt()](https://github.com/hhaslam11/Text-Fighter/blob/master/src/com/hotmail/kalebmarc/textfighter/main/Ui.java#L181-L186) method from the Ui class and the [do-while loop](https://github.com/hhaslam11/Text-Fighter/blob/fffca335f5a3e6772485667648c187dcfa0ec2df/src/com/hotmail/kalebmarc/textfighter/main/Casino.java#L138-L147) from the Casino class.

The int validator and loop seem to work fine. Maybe it has something to do with when it breaks out of the loop from the return statement? Not sure, I tried to help though haha!

**Comment by hhaslam11** [comment]
It might simply just be the Ui.pause() call after the prompt causing an error extra stop in the program.
I cant test this at the moment though, as im not at my computer

**Comment by CLEMENTJOHNSHAJI** [comment]
Yes, you are right. I fixed the issue by converting pause() function in Action.java
from
public static void pause(){
                        try{
                            Scanner pauseScan = new Scanner(System.in);
                            String temp = pauseScan.nextLine();
                            Ui.println(temp);
                        }catch (Exception e){
                                    //Blank for a reason - Not supposed to do anything.
                        }
     }
to
public static void pause(){
                        try{
                            Scanner pauseScan = new Scanner(System.in);
                             return;
                        }catch (Exception e){
                                    //Blank for a reason - Not supposed to do anything.
                        }
            }

**Comment by hhaslam11** [comment]
Doing that just makes the entire pause function essentially do nothing, making it not work at all (which you'll notice in other places the function is used. For example, when you attack an enemy, it won't pause the screen for the user to read the text before going back to the menu. 

The problem is that the Ui.pause call shouldnt be there at all. So, in `Casino.java`, change

```
if (bet > Coins.get()) {
   Ui.cls();
   bet = 0;
   Ui.println("You do not have enough coins. Please enter a smaller amount. (Or enter 0 to go back)");
   Ui.pause();
}
```

to

```
if (bet > Coins.get()) {
   Ui.cls();
   bet = 0;
   Ui.println("You do not have enough coins. Please enter a smaller amount. (Or enter 0 to go back)");
}
```

Hopefully that makes sense

**Comment by CLEMENTJOHNSHAJI** [comment]
Yes. On working on this, I realized the use of pause() function in other places and did the same change you have suggested in casino.java.

**Comment by CLEMENTJOHNSHAJI** [comment]
I am a beginner, and I am working on this project as part of my coursework. I have to update my contributions in git for the completion of my course. So can you please merge my request?
